[build]
builder = "nixpacks"

[build.nixpacks]
phases = {
  build = {
    cmds = ["pip install --upgrade pip && pip install -r requirements.txt"]
  }
}

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
